on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix test

  build-release-x64-debian10:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - name: Install erlang/elixir
        run: |
          apt-get update
          apt-get -y install wget gnupg build-essential
          wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
          dpkg -i erlang-solutions_2.0_all.deb
          apt-get update
          apt-get -y install esl-erlang
          apt-get -y install elixir
          mix local.hex --force
          mix local.rebar --force
          elixir --version
          apt list --installed
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get dependencies
        run: mix deps.get --only prod
      - name: Compile app
        run: MIX_ENV=prod mix compile
      - name: Prepare assets
        run: MIX_ENV=prod mix assets.deploy
      - name: Build release
        run: MIX_ENV=prod mix release
      - name: Create release tarball
        run: tar -cvf hyacinth-x64-debian10.tar hyacinth
        working-directory: _build/prod/rel
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: hyacinth-x64-debian10
          path: _build/prod/rel/hyacinth-x64-debian10.tar

  build-release-x64-centos-stream-8:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
      env:
        LC_ALL: en_US.UTF-8
    steps:
      - run: dnf config-manager --set-enabled powertools
      - run: dnf -y install epel-release epel-next-release
      - run: dnf -y install wget
      - run: wget https://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm
      - run: dnf -y install erlang-solutions-2.0-1.noarch.rpm
      - run: dnf -y install esl-erlang
      - run: erl -version
      - run: dnf -y install unzip
      - run: wget https://github.com/elixir-lang/elixir/releases/download/v1.14.0/elixir-otp-24.zip
      - run: mkdir ~/elixir
      - run: unzip elixir-otp-24.zip -d ~/elixir
      - run: ~/elixir/bin/elixir --version
      - run: locale
