on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix test

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - run: mix deps.get --only prod
      - run: MIX_ENV=prod mix compile
      - run: MIX_ENV=prod mix assets.deploy
      - run: MIX_ENV=prod mix release
      - uses: actions/upload-artifact@v3
        with:
          name: hyacinth-release-linux
          path: _build/prod/rel/hyacinth

  container-release-test:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - run: wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
      - run: sudo dpkg -i erlang-solutions_2.0_all.deb
      - run: sudo apt-get update
      - run: sudo apt-get install esl-erlang
      - run: sudo apt-get install elixir
      - run: elixir --version
      - uses: actions/checkout@v3
      - run: ls -al
