on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix test

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - run: mix deps.get --only prod
      - run: MIX_ENV=prod mix compile
      - run: MIX_ENV=prod mix assets.deploy
      - run: MIX_ENV=prod mix release
      - uses: actions/upload-artifact@v3
        with:
          name: hyacinth-release-linux
          path: _build/prod/rel/hyacinth

  container-release-test:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - name: Install erlang/elixir
        run: |
          apt-get update
          apt-get -y install wget gnupg build-essential
          wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
          dpkg -i erlang-solutions_2.0_all.deb
          apt-get update
          apt-get -y install esl-erlang
          apt-get -y install elixir
          mix local.hex --force
          mix local.rebar --force
          elixir --version
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: ls -al
      - name: Get dependencies
        run: mix deps.get --only prod
      - name: Compile app
        run: MIX_ENV=prod mix compile
      - name: Prepare assets
        run: MIX_ENV=prod mix assets.deploy
      - name: Build release
        run: MIX_ENV=prod mix release
