name: Create a release and upload built artifacts

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name'
        required: true

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --title ${{ inputs.tagName }} \
            --draft \
            ${{ inputs.tagName }}

  build-x64-centos-stream-8:
    uses: ./.github/workflows/build-x64-centos-stream-8.yml

  upload-x64-centos-stream-8:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: hyacinth-x64-centos-stream-8
      - name: Upload build to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.tagName }} hyacinth-x64-centos-stream-8.tar
